# Generated by Django 4.2.4 on 2023-09-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="desc",
            field=models.TextField(max_length=200),
        ),
    ]
