# Generated by Django 4.2.4 on 2023-09-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_alter_product_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shortDesc",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
